<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [2]:
import numpy as np

In [6]:
np.linspace(5,15,25)

array([ 5.        ,  5.41666667,  5.83333333,  6.25      ,  6.66666667,
        7.08333333,  7.5       ,  7.91666667,  8.33333333,  8.75      ,
        9.16666667,  9.58333333, 10.        , 10.41666667, 10.83333333,
       11.25      , 11.66666667, 12.08333333, 12.5       , 12.91666667,
       13.33333333, 13.75      , 14.16666667, 14.58333333, 15.        ])

In [7]:
my_linspace = np.linspace(5,15,9, retstep=True)

In [8]:
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [15]:
my_linspace[1]

1.25

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.zeros((7,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])