<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.5


In [3]:
my_list = [-15, 5, 10 , 9, 5]

my_array_from_list = np.array(my_list)

my_array_from_list

array([-15,   5,  10,   9,   5])

In [4]:
my_array_from_list * 10

array([-150,   50,  100,   90,   50])

In [5]:
my_tuple = (10, 5.5, 4.5j)
np.array(my_tuple)

array([10. +0.j ,  5.5+0.j ,  0. +4.5j])